version: "3.8"
services:
  nginx:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ../../front-end/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    # docker compose -p huyhoang-nginx up -d
